// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace T4.FileManager.NetCore.AcceptanceCriteria.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("UT004 Generate File with custom tool")]
    [NUnit.Framework.CategoryAttribute("db-9")]
    public partial class UT004GenerateFileWithCustomToolFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "db-9"};
        
#line 1 "UT004-Generate_File_With_CustomTool.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "UT004 Generate File with custom tool", "\tAs a developer\r\n\tI can generate code with the T4.FileManager and definied custom" +
                    " tool properties", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
#line hidden
#line 7
 await testRunner.GivenAsync("the file manager", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generate resx-File with custom tool (Dictionary)")]
        public async System.Threading.Tasks.Task GenerateResx_FileWithCustomToolDictionary()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Generate resx-File with custom tool (Dictionary)", "\tRemoved since version 2.0.0", tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Generate resx-File with custom tool (FileProperties)")]
        public async System.Threading.Tasks.Task GenerateResx_FileWithCustomToolFileProperties()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Generate resx-File with custom tool (FileProperties)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
await this.FeatureBackgroundAsync();
#line hidden
#line 13
 await testRunner.GivenAsync("the script \"ProjectTestFP.tt\" with the following content", "<#@ template debug=\"false\" hostspecific=\"true\" language=\"C#\" #>\r\n<#@ assembly nam" +
                        "e=\"System.Core\" #>\r\n<#@ import namespace=\"System.Linq\" #>\r\n<#@ import namespace=" +
                        "\"System.Text\" #>\r\n<#@ import namespace=\"System.Collections.Generic\" #>\r\n<#@ outp" +
                        "ut extension=\".txt\" #>\r\n<#@ include file=\"$(TargetDir)\\T4.FileManager.VisualStud" +
                        "io.ttinclude\" #>\r\n<#\r\nvar document = new List<string[]>();\r\ndocument.Add(new str" +
                        "ing[] { \"FirstName\", \"Vorname\", \"Angaben zum Vornamen\"});\r\ndocument.Add(new stri" +
                        "ng[] { \"LastName\", \"Nachname\", \"Angaben zum Nachnamen\"});\r\ndocument.Add(new stri" +
                        "ng[] { \"Street\", \"Strasse\", \"Angaben zur Strasse\"});\r\n\r\nvar fileManager = Templa" +
                        "teFileManager.Create(this);\r\n\r\nvar fp = new FileProperties();\r\nfp.CustomTool = \"" +
                        "ResXFileCodeGenerator\";\r\n\r\nfileManager.StartNewFile(\"ProjectTestFP.resx\", \"\", \"\"" +
                        ", fp); \r\n#>\r\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<root>\r\n<xsd:schema id=\"roo" +
                        "t\" xmlns=\"\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:msdata=\"urn:schem" +
                        "as-microsoft-com:xml-msdata\">\r\n  <xsd:element name=\"root\" msdata:IsDataSet=\"true" +
                        "\">\r\n    <xsd:complexType>\r\n      <xsd:choice maxOccurs=\"unbounded\">\r\n        <xs" +
                        "d:element name=\"data\">\r\n          <xsd:complexType>\r\n            <xsd:sequence>\r" +
                        "\n              <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" msdata:" +
                        "Ordinal=\"1\" />\r\n              <xsd:element name=\"comment\" type=\"xsd:string\" minO" +
                        "ccurs=\"0\" msdata:Ordinal=\"2\" />\r\n            </xsd:sequence>\r\n            <xsd:a" +
                        "ttribute name=\"name\" type=\"xsd:string\" msdata:Ordinal=\"1\" />\r\n            <xsd:a" +
                        "ttribute name=\"type\" type=\"xsd:string\" msdata:Ordinal=\"3\" />\r\n            <xsd:a" +
                        "ttribute name=\"mimetype\" type=\"xsd:string\" msdata:Ordinal=\"4\" />\r\n          </xs" +
                        "d:complexType>\r\n        </xsd:element>\r\n        <xsd:element name=\"resheader\">\r\n" +
                        "          <xsd:complexType>\r\n            <xsd:sequence>\r\n              <xsd:elem" +
                        "ent name=\"value\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"1\" />\r\n        " +
                        "    </xsd:sequence>\r\n            <xsd:attribute name=\"name\" type=\"xsd:string\" us" +
                        "e=\"required\" />\r\n          </xsd:complexType>\r\n        </xsd:element>\r\n      </x" +
                        "sd:choice>\r\n    </xsd:complexType>\r\n  </xsd:element>\r\n</xsd:schema>\r\n<resheader " +
                        "name=\"resmimetype\">\r\n  <value>text/microsoft-resx</value>\r\n</resheader>\r\n<reshea" +
                        "der name=\"version\">\r\n  <value>1.3</value>\r\n</resheader>\r\n<resheader name=\"reader" +
                        "\">\r\n  <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=" +
                        "2.0.3500.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>\r\n</resheade" +
                        "r>\r\n<resheader name=\"writer\">\r\n  <value>System.Resources.ResXResourceWriter, Sys" +
                        "tem.Windows.Forms, Version=2.0.3500.0, Culture=neutral, PublicKeyToken=b77a5c561" +
                        "934e089</value>\r\n</resheader>\r\n<# \r\nfor (int idx = 0; idx < document.Count; idx+" +
                        "+)\r\n{\r\nvar item = document[idx];\r\n#>\r\n<data name=\"<#= item[0] #>\" xml:space=\"pre" +
                        "serve\">\r\n  <value><#= item[1] #></value>\r\n  <comment><#= item[2] #></comment>\r\n<" +
                        "/data>\t \r\n<#} #>\r\n</root>\r\n<#\r\n\r\n\r\nfileManager.Process();\r\n#>", ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 93
 await testRunner.WhenAsync("I run the script", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "File"});
                table10.AddRow(new string[] {
                            "ProjectTestFP.resx"});
                table10.AddRow(new string[] {
                            "ProjectTestFP.Designer.cs"});
#line 94
 await testRunner.ThenAsync("the following files are generated:", ((string)(null)), table10, "Then ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "File"});
                table11.AddRow(new string[] {
                            "ProjectTestFP.resx"});
#line 98
 await testRunner.AndAsync("the custom tool is set to \"ResXFileCodeGenerator\" for the following files:", ((string)(null)), table11, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
